# Generated by Django 4.2.2 on 2023-10-29 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_transaction_transaction_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcode',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
