# Generated by Django 3.2.23 on 2024-03-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_paymentcode_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
